#!/usr/bin/env python

import lx

userValues = [
    ['exportFile_sw', lx.symbol.sTYPE_BOOLEAN, False],
    ['scanFiles_sw', lx.symbol.sTYPE_BOOLEAN, False],
    ['exportEach_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportHierarchy_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['triple_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['resetPos_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['resetRot_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['resetSca_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['resetShe_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezePos_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezeRot_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezeSca_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezeShe_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezeGeo_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['freezeInstance_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['posX', lx.symbol.sTYPE_FLOAT, True],
    ['posY', lx.symbol.sTYPE_FLOAT, True],
    ['posZ', lx.symbol.sTYPE_FLOAT, True],
    ['rotX', lx.symbol.sTYPE_FLOAT, True],
    ['rotY', lx.symbol.sTYPE_FLOAT, True],
    ['rotZ', lx.symbol.sTYPE_FLOAT, True],
    ['scaX', lx.symbol.sTYPE_FLOAT, True],
    ['scaY', lx.symbol.sTYPE_FLOAT, True],
    ['scaZ', lx.symbol.sTYPE_FLOAT, True],
    ['smoothAngle_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['smoothAngle', lx.symbol.sTYPE_FLOAT, True],
    ['hardenUvBorder_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['uvMapName', lx.symbol.sTYPE_STRING, True],
    ['exportFormatFbx_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatObj_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatLxo_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatLwo_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatAbc_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatAbchdf_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatDae_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatDxf_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormat3dm_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportFormatGeo_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['exportCageMorph_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['cageMorphMapName', lx.symbol.sTYPE_STRING, True],
    ['applyMorphMap_sw', lx.symbol.sTYPE_BOOLEAN, True],
    ['morphMapName', lx.symbol.sTYPE_STRING, True],
    ['openDestFolder_sw', lx.symbol.sTYPE_BOOLEAN, True]
    ]
