#!/usr/bin/env python

import lx, modo
import os
from Tila_BatchExportModule import dialog


def enum(*args):
	enums = dict(zip(args, range(len(args))))
	return type('Enum', (), enums)


TILA_BATCH_EXPORT = "tila.batchexport"
TILA_BATCH_TRANSFORM = "tila.batchtransform"
TILA_BATCH_FOLDER = "tila.batchfolder"
TILA_OPEN_EXPORT_FOLDER = "tila.openexportfolder"
TILA_EXPORT_PRESET = "tila.exportpreset"
TILA_EXPORT_SELECTED = "tila.exportselected"
TILA_FREEZE_REPLICATOR = 'tila.freezereplicator'

TILA_PRESET_NAME = 'presetName'
TILA_EXPORT_VISIBLE = 'exportVisible_sw'

TILA_DUPLICATE_SUFFIX = '_tila_duplicate'
TILA_BACKUP_SUFFIX = '_tila_backup'

TILA_MESSAGEPREFIX = 'TILA_BATCHEXPORT'

REFRESH_ASTERISK_NOTIFIER = "tila.export.refreshAsteriskNotifier"


def set_import_setting():
	lx.eval('user.value sceneio.obj.import.static false')
	lx.eval('user.value sceneio.obj.import.separate.meshes false')
	lx.eval('user.value sceneio.obj.import.suppress.dialog true')
	lx.eval('user.value sceneio.obj.import.units centimeters')


userValues = [
	[TILA_EXPORT_VISIBLE, lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFile_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['scanFiles_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['scanFolder_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportEach_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportHierarchy_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['triple_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['mergeMesh_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['askBeforeOverride_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['assignMaterialPerUDIMTile_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['UDIMTextureName', lx.symbol.sTYPE_STRING, True, 'Texture'],
	['resetPos_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['resetRot_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['resetSca_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['resetShe_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezePos_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeRot_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeSca_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeShe_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeGeo_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeInstance_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeMeshOp_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['freezeReplicator_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['pos_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['posX', lx.symbol.sTYPE_FLOAT, True, 0],
	['posY', lx.symbol.sTYPE_FLOAT, True, 0],
	['posZ', lx.symbol.sTYPE_FLOAT, True, 0],
	['rot_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['rotX', lx.symbol.sTYPE_FLOAT, True, 0],
	['rotY', lx.symbol.sTYPE_FLOAT, True, 0],
	['rotZ', lx.symbol.sTYPE_FLOAT, True, 0],
	['sca_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['scaX', lx.symbol.sTYPE_FLOAT, True, 1],
	['scaY', lx.symbol.sTYPE_FLOAT, True, 1],
	['scaZ', lx.symbol.sTYPE_FLOAT, True, 1],
	['smoothAngle_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['smoothAngle', lx.symbol.sTYPE_FLOAT, True, 40],
	['hardenUvBorder_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['uvMapName', lx.symbol.sTYPE_STRING, True, 'Texture'],
	['exportCageMorph_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['cageMorphMapName', lx.symbol.sTYPE_STRING, True, 'Cage'],
	['exportMorphMap_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['applyMorphMap_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['morphMapName', lx.symbol.sTYPE_STRING, True, 'Exploded'],
	['openDestFolder_sw', lx.symbol.sTYPE_BOOLEAN, True, 1],
	['createFormatSubfolder_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['processSubfolder_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['subfolderDepth', lx.symbol.sTYPE_INTEGER, True, 1],
	['formatFilter', lx.symbol.sTYPE_STRING, True, 'fbx,obj'],
	['filenamePattern', lx.symbol.sTYPE_STRING, True, '<file>_<item>'],
	['exportFormatLxo_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatLwo_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatFbx_sw', lx.symbol.sTYPE_BOOLEAN, True, 1],
	['exportFormatObj_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatAbc_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatAbchdf_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatDae_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatDxf_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormat3dm_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatGeo_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatStl_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatX3d_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatSvg_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	['exportFormatPlt_sw', lx.symbol.sTYPE_BOOLEAN, True, 0],
	[TILA_PRESET_NAME, lx.symbol.sTYPE_STRING, True, 'default']
]


def create_one_item_of_each_type():
	service = lx.service

	obj = service.Scene().ItemTypeName

	# print obj
	# print obj.__doc__
	# print dir(obj)

	ignoreList = ['render', 'scene', 'polyRender']

	for i in xrange(1000):
		if obj(i) is not None and obj(i) not in ignoreList:
			try:
				lx.eval('item.create {}'.format(obj(i)))
			except:
				continue


def print_all_item_name():
	scn = modo.Scene()

	for item in scn.items():
		print item.name


genericName = [	"Group" ,
				"Bezier Effector" ,
				"Spline Effector" ,
				"Slack Effector" ,
				"mediaClip" ,
				"Image" ,
				"imageLayer" ,
				"imageFolder" ,
				"Gradient Fill" ,
				"Locator" ,
				"Mesh" ,
				"Camera" ,
				"Constant" ,
				"Capsule" ,
				"Grid" ,
				"Dots" ,
				"Checker" ,
				"Noise" ,
				"Cellular" ,
				"Wood" ,
				"Weave" ,
				"Ripples" ,
				"Gradient" ,
				"Wireframe Texture" ,
				"Counter 1" ,
				"Counter 2" ,
				"UV LEDs" ,
				"Box" ,
				"Circular" ,
				"Corners" ,
				"Cubic" ,
				"Dimples" ,
				"Grid_2" ,
				"Iris" ,
				"Linear" ,
				"Polygon" ,
				"Radial" ,
				"Ring" ,
				"Random Linear" ,
				"Spiral" ,
				"Star" ,
				"Agate" ,
				"Bozo" ,
				"Cruddy" ,
				"Dented" ,
				"Etched" ,
				"Flow Bozo" ,
				"Granite" ,
				"Hybrid" ,
				"Lump" ,
				"Marble Noise" ,
				"Marble Vein" ,
				"Multi-Fractal" ,
				"Pebbles" ,
				"Puffy Clouds" ,
				"Ridged" ,
				"Scar" ,
				"Scruffed" ,
				"Strata" ,
				"Stucco" ,
				"Vector Bozo" ,
				"Wrapped fBm" ,
				"fBm" ,
				"Art Deco" ,
				"Blister" ,
				"Branches" ,
				"Caustic" ,
				"Cellular_2" ,
				"Cheesy" ,
				"Concrete" ,
				"Crackle" ,
				"Dirt" ,
				"Disturbed" ,
				"Easy Wood" ,
				"Electric" ,
				"Fire" ,
				"Firewall" ,
				"Hardwood" ,
				"Membrane" ,
				"Minky" ,
				"Scatter" ,
				"Sin Blob" ,
				"Veins" ,
				"Wires" ,
				"Worm Vein" ,
				"Peel" ,
				"Plates" ,
				"Rivet Rust" ,
				"Rivets" ,
				"Rust" ,
				"Smear" ,
				"Easy Gradient" ,
				"Regional HSV" ,
				"Camo" ,
				"Crumpled" ,
				"Dino Skin" ,
				"Disease" ,
				"Frog Skin" ,
				"Grainy Wood" ,
				"Leather" ,
				"Monster" ,
				"Pastella" ,
				"Peened" ,
				"Scratches" ,
				"Blast" ,
				"Coriolis" ,
				"Flare" ,
				"Gas Giant" ,
				"Glint" ,
				"Hurricane" ,
				"Nurnies" ,
				"Planet" ,
				"Planet Clouds" ,
				"Rings" ,
				"Star Field" ,
				"Swirl" ,
				"Terra" ,
				"Windows" ,
				"Basket" ,
				"Bath Tile" ,
				"Bricks" ,
				"Checks" ,
				"Cornerless" ,
				"Cubes" ,
				"Dash Line" ,
				"Diamond Deck" ,
				"Fish Scales" ,
				"Hex Tile" ,
				"Lattice 1" ,
				"Lattice 2" ,
				"Lattice 3" ,
				"Mosaic" ,
				"Oct Tile" ,
				"Parquet" ,
				"Paving" ,
				"Plaid" ,
				"Planks" ,
				"Ribs" ,
				"Rounded Tile" ,
				"Shingles" ,
				"Spots" ,
				"Stamped" ,
				"Tacos" ,
				"Tartan" ,
				"Tiler" ,
				"Tri Checks" ,
				"Tri Hexes" ,
				"Tri Tile" ,
				"Wall" ,
				"Drip Drop" ,
				"Rain" ,
				"Ripples_2" ,
				"Surf" ,
				"Waves" ,
				"Windy Waves" ,
				"Bias Gain" ,
				"Fresnel" ,
				"Gamma" ,
				"Gaussian" ,
				"Impulse" ,
				"Noise_2" ,
				"Ramp" ,
				"Rounded" ,
				"S-Curve" ,
				"Sawtooth" ,
				"Scallop" ,
				"Sine" ,
				"Smooth" ,
				"Smooth Impulse" ,
				"Smooth Step" ,
				"Staircase" ,
				"RPC Texture" ,
				"RT Curvature" ,
				"Halftone Material" ,
				"Gabor Noise" ,
				"Poisson Cells" ,
				"RPC Texture_2" ,
				"Backdrop Item" ,
				"Texture Group" ,
				"Group Locator" ,
				"Force" ,
				"Falloff" ,
				"baseVolume" ,
				"Deformer" ,
				"Channel Handle" ,
				"ikSolver" ,
				"Directional Light" ,
				"Point Light" ,
				"Spot Light" ,
				"Area Light" ,
				"Cylinder Light" ,
				"Dome Light" ,
				"Mesh Light" ,
				"Portal" ,
				"Photometric Light" ,
				"Static Mesh" ,
				"Proxy" ,
				"Replicator" ,
				"Surface Particle Generator" ,
				"Particle Simulation" ,
				"Volume" ,
				"Sprite" ,
				"Render Boolean" ,
				"Blob" ,
				"Particle Cloud" ,
				"Realflow Particles" ,
				"Deform" ,
				"Particle Operator" ,
				"AlembicFile" ,
				"Alembic Curves" ,
				"AlembicCloud" ,
				"Alembic Mesh" ,
				"Curve Particle Generator" ,
				"Capsule Falloff" ,
				"Radial Falloff" ,
				"Linear Falloff" ,
				"Texture Falloff" ,
				"Morph Influence" ,
				"Weight Container" ,
				"Bend Effector" ,
				"Bezier Falloff" ,
				"Bezier Node" ,
				"Curve Constraint Effector" ,
				"Lag Effector" ,
				"Lattice Effector" ,
				"Magnet Effector" ,
				"Spline Falloff" ,
				"Vortex Effector" ,
				"Soft Lag" ,
				"anchor" ,
				"Dynamic Collision Emitter" ,
				"Collision Emitter" ,
				"Constraint" ,
				"Constraint Modifier" ,
				"Dynamic Fluid" ,
				"Hinge" ,
				"Pin" ,
				"Point" ,
				"Procedural Shatter" ,
				"Dynamic Replicator" ,
				"Slide Hinge" ,
				"solver" ,
				"Spring" ,
				"Linear Force" ,
				"Radial Force" ,
				"Drag Force" ,
				"Turbulence Force" ,
				"Vortex Force" ,
				"Wind Force" ,
				"Curve Force" ,
				"Newton Force" ,
				"Fractal Gasket" ,
				"Gear" ,
				"Ground Plane" ,
				"Full Body IK" ,
				"Sphere" ,
				"Radial Emitter" ,
				"Curve Emitter" ,
				"Surface Emitter" ,
				"Source Emitter" ,
				"Collector / Emitter" ,
				"Terminator" ,
				"Particle Flocking" ,
				"CSV Point Cache" ,
				"Particle Audio Modifier" ,
				"Particle Modifier" ,
				"Particle Expression Modifier" ,
				"Particle Generator" ,
				"Particle Look At Modifier" ,
				"Particle Random Modifier" ,
				"Particle Sieve Modifier" ,
				"Particle Step Modifier" ,
				"Poisson Particles" ,
				"Rock" ,
				"RPC Mesh" ,
				"Deferred Mesh" ,
				"Deferred Surface" ,
				"VDBVoxel" ,
				"SubDFusion" ,
				"CanvasPI" ,
				"surf.sample" ,
				"Dynamic Collider" ,
				"Render" ,
				"Environment" ,
				"Texture Layer" ,
				"Bake Items" ,
				"Lights" ,
				"Environments" ,
				"Nodes" ,
				"Library" ,
				"Folder" ,
				"Base Material" ,
				"Material" ,
				"Material" ,
				"Group" ,
				"RPC Material" ,
				"Constant" ,
				"Base Shader" ,
				"Shader" ,
				"Matcap Shader" ,
				"Unreal Material" ,
				"Unity Material" ,
				"Projection Shader" ,
				"Projection Texture" ,
				"Final Color Output" ,
				"Alpha Output" ,
				"Output" ,
				"Capsule" ,
				"Process" ,
				"Vertex Map Texture" ,
				"Variation Texture" ,
				"Tension Texture" ,
				"Grid" ,
				"Dots" ,
				"Checker" ,
				"Noise" ,
				"Cellular" ,
				"Wood" ,
				"Weave" ,
				"Ripples" ,
				"Occlusion" ,
				"Gradient" ,
				"Light Material" ,
				"Environment Material" ,
				"Surface Generator" ,
				"Fur Material" ,
				"Wireframe Texture" ,
				"Counter 1" ,
				"Counter 2" ,
				"UV LEDs" ,
				"Box" ,
				"Circular" ,
				"Corners" ,
				"Cubic" ,
				"Dimples" ,
				"Grid" ,
				"Iris" ,
				"Linear" ,
				"Polygon" ,
				"Radial" ,
				"Ring" ,
				"Random Linear" ,
				"Spiral" ,
				"Star" ,
				"Agate" ,
				"Bozo" ,
				"Cruddy" ,
				"Dented" ,
				"Etched" ,
				"Flow Bozo" ,
				"Granite" ,
				"Hybrid" ,
				"Lump" ,
				"Marble Noise" ,
				"Marble Vein" ,
				"Multi-Fractal" ,
				"Pebbles" ,
				"Puffy Clouds" ,
				"Ridged" ,
				"Scar" ,
				"Scruffed" ,
				"Strata" ,
				"Stucco" ,
				"Vector Bozo" ,
				"Wrapped fBm" ,
				"fBm" ,
				"Art Deco" ,
				"Blister" ,
				"Branches" ,
				"Caustic" ,
				"Cellular" ,
				"Cheesy" ,
				"Concrete" ,
				"Crackle" ,
				"Dirt" ,
				"Disturbed" ,
				"Easy Wood" ,
				"Electric" ,
				"Fire" ,
				"Firewall" ,
				"Hardwood" ,
				"Membrane" ,
				"Minky" ,
				"Scatter" ,
				"Sin Blob" ,
				"Veins" ,
				"Wires" ,
				"Worm Vein" ,
				"Peel" ,
				"Plates" ,
				"Rivet Rust" ,
				"Rivets" ,
				"Rust" ,
				"Smear" ,
				"Easy Gradient" ,
				"Regional HSV" ,
				"Camo" ,
				"Crumpled" ,
				"Dino Skin" ,
				"Disease" ,
				"Frog Skin" ,
				"Grainy Wood" ,
				"Leather" ,
				"Monster" ,
				"Pastella" ,
				"Peened" ,
				"Scratches" ,
				"Blast" ,
				"Coriolis" ,
				"Flare" ,
				"Gas Giant" ,
				"Glint" ,
				"Hurricane" ,
				"Nurnies" ,
				"Planet" ,
				"Planet Clouds" ,
				"Rings" ,
				"Star Field" ,
				"Swirl" ,
				"Terra" ,
				"Windows" ,
				"Basket" ,
				"Bath Tile" ,
				"Bricks" ,
				"Checks" ,
				"Cornerless" ,
				"Cubes" ,
				"Dash Line" ,
				"Diamond Deck" ,
				"Fish Scales" ,
				"Hex Tile" ,
				"Lattice 1" ,
				"Lattice 2" ,
				"Lattice 3" ,
				"Mosaic" ,
				"Oct Tile" ,
				"Parquet" ,
				"Paving" ,
				"Plaid" ,
				"Planks" ,
				"Ribs" ,
				"Rounded Tile" ,
				"Shingles" ,
				"Spots" ,
				"Stamped" ,
				"Tacos" ,
				"Tartan" ,
				"Tiler" ,
				"Tri Checks" ,
				"Tri Hexes" ,
				"Tri Tile" ,
				"Wall" ,
				"Drip Drop" ,
				"Rain" ,
				"Ripples" ,
				"Surf" ,
				"Waves" ,
				"Windy Waves" ,
				"Bias Gain" ,
				"Fresnel" ,
				"Gamma" ,
				"Gaussian" ,
				"Impulse" ,
				"Noise" ,
				"Ramp" ,
				"Rounded" ,
				"S-Curve" ,
				"Sawtooth" ,
				"Scallop" ,
				"Sine" ,
				"Smooth" ,
				"Smooth Impulse" ,
				"Smooth Step" ,
				"Staircase" ,
				"Cel Material" ,
				"Hair Material" ,
				"RPC Texture" ,
				"RT Curvature" ,
				"Cel Edges Material" ,
				"Halftone Material" ,
				"Iridescence Material" ,
				"ThinFilm Material" ,
				"Skin Material" ,
				"Gabor Noise" ,
				"Poisson Cells" ,
				"Action Clip" ,
				"actionpose" ,
				"Transform" ,
				"Position" ,
				"Rotation" ,
				"Scale" ,
				"Shear" ,
				"Core Transform" ,
				"Deform" ,
				"MDD Deformer" ,
				"Deform" ,
				"Normalizing Folder" ,
				"Deform Folder" ,
				"shader" ,
				"Shader Inputs" ,
				"Raycast" ,
				"Illuminate" ,
				"Ray Type" ,
				"Texture Switch" ,
				"Scene" ,
				"Channel Effect" ,
				"Float Channel Effect" ,
				"Matrix Channel Effect" ,
				"Channel Modifier" ,
				"Relationship" ,
				"Vertex Position" ,
				"Path Position Constraint" ,
				"Intersect" ,
				"Position Constraint" ,
				"Dynamic Parent" ,
				"Direction Constraint" ,
				"Basic Math" ,
				"Square Root" ,
				"Sin" ,
				"Add" ,
				"Distance Constraint" ,
				"Revolve" ,
				"Measure Distance" ,
				"Measure Angle" ,
				"A is equal to B" ,
				"Matrix Blend" ,
				"Matrix Compose" ,
				"Matrix Vector" ,
				"Channel Oscillator" ,
				"Channel Noise" ,
				"Color HSV" ,
				"Color Kelvin" ,
				"Time" ,
				"Dual Joint Planar IK" ,
				"Clamp" ,
				"Color Blend" ,
				"Color Gamma" ,
				"Color Invert" ,
				"Math:Constant" ,
				"Time Cycler" ,
				"Expression" ,
				"Time Offset: Float" ,
				"Time Warp: Float" ,
				"Generate ID" ,
				"Linear Blend" ,
				"Add" ,
				"Matrix Construct" ,
				"Matrix From Euler" ,
				"Matrix Invert" ,
				"Time Offset: Matrix" ,
				"Matrix To Euler" ,
				"Matrix Transpose" ,
				"Matrix Vector Multiply" ,
				"Time Warp: Matrix" ,
				"Quaternion Conjugate" ,
				"Quaternion From Axis-Angle" ,
				"Quaternion From Euler" ,
				"Quaternion From Matrix" ,
				"Quaternion Get Value" ,
				"Quaternion Math" ,
				"Quaternion Normalize" ,
				"Quaternion Set Value" ,
				"Quaternion Slerp" ,
				"Quaternion To Axis-Angle" ,
				"Quaternion To Euler" ,
				"Quaternion To Matrix" ,
				"Quaternion Vector Multiply" ,
				"Random" ,
				"Simple Kinematics" ,
				"Smooth" ,
				"Sound" ,
				"Measure Speed" ,
				"String Compose" ,
				"String Find and Replace" ,
				"String Switch" ,
				"Switch" ,
				"Vector:Multiply By Scalar" ,
				"Vector:Magnitude" ,
				"Vector:Orthogonalize" ,
				"Vector:Reflection" ,
				"Measure Velocity" ,
				"Channel Waveform" ,
				"Randomize ID" ,
				"Fusion Union" ,
				"Fusion Intersect" ,
				"Fusion Subtract" ,
				"Encode String" ,
				"Item Modifier" ,
				"Channel Modifier" ,
				"Color Correct" ,
				"Curve Probe" ,
				"Mesh Info" ,
				"Particle Constraint:Position" ,
				"Falloff Probe" ,
				"Channel Probe" ,
				"Particle Constraint:Rotation" ,
				"String Constant" ,
				"UV Constraint" ,
				"ADSR Envelope" ,
				"Camera Plane" ,
				"Camera Match" ,
				"CanvasIM" ,
				"Simulation Flow-Through" ,
				"Simulation Follower" ,
				"Simulation Latch" ,
				"Bake Item" ,
				"Output Baking" ,
				"Texture Baking" ,
				"Tool Operation" ,
				"Mesh Operation" ,
				"Edges to Curves" ,
				"Lace Geometry" ,
				"Curve Fill" ,
				"UV Transform" ,
				"Transfer Vertex Map" ,
				"Sculpt Modifier" ,
				"Curve Rebuild" ,
				"Array Generator" ,
				"Helix Generator" ,
				"Linear Generator" ,
				"Merge Meshes" ,
				"Mirror Generator" ,
				"Path Generator" ,
				"Pen Generator" ,
				"Transform UV Map" ,
				"Scatter Generator" ,
				"Assign Selection Set" ,
				"Axis Drill" ,
				"Boolean" ,
				"Delete" ,
				"Freeze" ,
				"Material Tag" ,
				"Smooth_2" ,
				"Solid Drill" ,
				"Symmetrize" ,
				"Content Preset" ,
				"Circle" ,
				"Diamond" ,
				"Ellipse" ,
				"N-Sided" ,
				"Rectangle" ,
				"Star" ,
				"Detriangulate" ,
				"Edge Bevel" ,
				"Edge Extrude" ,
				"Clone Effector" ,
				"Slice Effector" ,
				"Sweep Effector" ,
				"Path Segment Generator" ,
				"Set Work Plane" ,
				"Polygon Bevel" ,
				"Polygon Extrude" ,
				"Axis Slice" ,
				"Slice" ,
				"Polygon Reduce" ,
				"Smooth Shift" ,
				"Capsule" ,
				"Cone" ,
				"Cube" ,
				"Cylinder" ,
				"Ellipsoid" ,
				"Sphere_2" ,
				"Text" ,
				"Toroid" ,
				"Subdivide" ,
				"Symmetry" ,
				"Vertex Bevel" ,
				"Vertex Extrude" ,
				"Vertex Merge" ,
				"Thicken" ,
				"Curve Extrude" ,
				"Radial Sweep" ,
				"Pen Extrude" ,
				"Clone" ,
				"Array" ,
				"Radial Array" ,
				"Scatter Clone" ,
				"Curve Clone" ,
				"Pen Clone" ,
				"Curve Slice" ,
				"Pen Slice" ,
				"Mirror" ,
				"Python Mesh Op" ,
				"Selection Operation" ,
				"Select By Falloff" ,
				"Selection Operator : Vertex" ,
				"Selection Operator : Edge" ,
				"Selection Operator : Polygon" ,
				"Selection Type Filter" ,
				"Select By Border" ,
				"Boundary Edges" ,
				"Grow / Shrink" ,
				"Select By Index" ,
				"Invert" ,
				"Select By Range" ,
				"Select By Selection Set" ,
				"Schematic Node" ,
				"audioFile" ,
				"MDD Influence" ,
				"Item Influence" ,
				"General Influence" ,
				"Push Influence" ,
				"Wrap Influence" ,
				"ABCCurvesDeform.sample" ,
				"ABCdeform.sample" ]


def get_generic_name_dict(arr):
	dict = {}
	for o in arr:
		dict[o] = o.lower()
	return dict


genericNameDict = get_generic_name_dict(genericName)


exportTypes = [
	['lxo', '$LXOB'],
	['lwo', '$NLWO2'],
	['fbx', 'fbx'],
	['obj', 'wf_OBJ'],
	['abc', 'Alembic'],
	['abc', 'AlembicHDF'],
	['dae', 'COLLADA_141'],
	['dxf', 'DXF'],
	['3dm', 'THREEDM'],
	['geo', 'vs_GEO'],
	['stl', 'pySTLScene2'],
	['x3d', '$X3D'],
	['svg', 'SVG_SceneSaver'],
	['plt', 'HPGL_PLT']
]


compatibleImportFormat = [exportTypes[i][0] for i in xrange(len(exportTypes))]


itemType = {'MESH': 'mesh',
			'MESH_INSTANCE': 'meshInst',
			'MESH_FUSION': 'sdf.item',
			'CAMERA': 'camera',
			'LIGHT': 'light',
			'TEXTURE_LOCATOR': 'txtrLocator',
			'BACKDROP': 'backdrop',
			'GROUP_LOCATOR': 'groupLocator',
			'REPLICATOR': 'replicator',
			'SURFACE_GENERATOR': 'surfGen',
			'LOCATOR': 'locator',
			'DEFORM': 'deform',
			'LOCATOR_DEFORM': 'locdeform',
			'DEFORM_GROUP': 'deformGroup',
			'DEFORM_MDD2': 'deformMDD2',
			'MORPH_DEFORM': 'morphDeform',
			'ITEM_INFLUENCE': 'itemInfluence',
			'GEN_INFLUENCE': 'genInfluence',
			'DEFORM_PUSH': 'deform.push',
			'DEFORM_WARP': 'deform.wrap',
			'SOFT_LAG': 'softLag',
			'ABC_CURVE_DEFORM': 'ABCCurvesDeform.sample',
			'ABC_DEFORM': 'ABCdeform.sample',
			'FORCE_ROOT': 'force.root',
			'BASE_VOLUME': 'baseVolume',
			'CHANNEL_MODIFY': 'chanModify',
			'ITEM_MODIFY': 'itemModify',
			'MESH_OPERATION': 'meshoperation',
			'CHANNEL_EFFECT': 'chanEffect',
			'DEFAULT_SHADER': 'defaultShader',
			'ADVANCED_MATERIAL': 'advancedMaterial'}

compatibleItemType = {'MESH': 'mesh',
					  'MESH_INSTANCE': 'meshInst',
					  'REPLICATOR': 'replicator',
					  'GROUP_LOCATOR': 'groupLocator',
					  'LOCATOR': 'locator'}

defaultExportSettings = {'FBX_EXPORT_TYPE': lx.eval('user.value sceneio.fbx.save.exportType ?'),
						 'FBX_SURFACE_REFINING': lx.eval('user.value sceneio.fbx.save.surfaceRefining ?'),
						 'FBX_FORMAT': lx.eval('user.value sceneio.fbx.save.format ?')}

defaultImportSettings = {'OBJ_STATIC': lx.eval('user.value sceneio.obj.import.static ?'),
						 'OBJ_SEPARATE_MESH': lx.eval('user.value sceneio.obj.import.separate.meshes ?'),
						 'OBJ_SUPRESS_DIALOG': lx.eval('user.value sceneio.obj.import.suppress.dialog ?'),
						 'OBJ_UNIT': lx.eval('user.value sceneio.obj.import.units ?')}

indexStyle = ['brak-sp', 'brak', 'sp', 'uscore', 'none']

g_dialog_svc = lx.service.StdDialog()
g_msg_svc    = lx.service.Message ()
g_msg        = lx.object.Message (g_msg_svc.Allocate ())

kit_prefix = 'tilaBExp.'
preset_hash = '70945661220'

curr_path = os.path.dirname(os.path.realpath(__file__))
root_path = dialog.parentPath(curr_path)
config_path = os.path.join(root_path, "Tila_Config")
preset_path = os.path.join(root_path, "Tila_Preset")


config_filename = 'tila_batchexport.cfg'
config_root = 'configuration'
config_sub_element = 'atom'
config_last_directory = 'LastDirectory'
config_export_path = 'ExportPath'
config_browse_src_path = 'BrowseSrcPath'
config_browse_dest_path = 'BrowseDestPath'
config_export_settings = 'ExportSettings'

config_file_path = os.path.join(config_path, config_filename)
